### ISSUE TITLE
0x9C and 0x9E I2C PMIC offsets: they are specific charger registers 0x1C and 0x1E 

### ISSUE THREAD

**Issue by michelesponchiado** [olback/h7-bootloader-rev#5]
Hi, 
if you check the PMIC datasheet, par 12.2  "Specific Charger Registers (Offset is 0x80)", you can see that the registers at offset 0x9C and 0x9E are the charger registers at 0x1C and 0x1E:

-  Register LED_PWM - ADDR 0x1C set to 0x80 --> LED driver enable
-  Register LED_CNFG - ADDR 0x1E set to 0x20 -->   LED controlled via software

overall, I think the settings are meant to enable the LED indicator drive output via software

**Comment by olback** [comment]
Thanks!
